# Color themes

rockin:
  name: Rockin'
  description: RockinDev color theme

  light:
    --error-color: hsl(30deg 100% 50%)
    --text-color: hsl(0deg 0% 20%)
    --muted-text-color: hsl(0deg 0% 40%)
    --background-color: hsl(0deg 0% 100%)
    --callout-color: hsl(0deg 0% 97%)
    --highlighted-callout-color: hsl(0deg 0% 90%)
    --border-color: hsl(0deg 0% 80%)

  dark:
    --error-color: hsl(30deg 100% 50%)
    --text-color: hsl(0deg 0% 100%)
    --muted-text-color: hsl(0deg 0% 80%)
    --background-color: hsl(0deg 0% 5%)
    --callout-color: hsl(0deg 0% 15%)
    --highlighted-callout-color: hsl(0deg 0% 25%)
    --border-color: hsl(0deg 0% 40%)
