name: Deploy RockinDev website to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy RockinDev website to AWS

    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      id-token: write
      contents: read

    env:
      ENV: prod
      BUILD_DIR: dist

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm package manager
      uses: pnpm/action-setup@v4

    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build website
      env:
        THEME: ${{ vars.THEME }}
        APP_BASE_URL: ${{ vars.APP_BASE_URL }}
        BLOG_BASE_URL: ${{ vars.BLOG_BASE_URL }}
        JOB_BOARD_URL: ${{ vars.JOB_BOARD_URL }}
        API_BASE_URL: ${{ vars.API_BASE_URL }}
        LINKEDIN_URL: ${{ vars.LINKEDIN_URL }}
        GIT_HUB_URL: ${{ vars.GIT_HUB_URL }}
        TWITTER_URL: ${{ vars.TWITTER_URL }}
        ANALYTICS_ENABLED: ${{ vars.ANALYTICS_ENABLED }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      run: |
        pnpm install
        pnpm generate
        cp config/robots.${ENV}.txt dist/robots.txt

    - name: Deploy website to S3
      run: aws s3 sync $BUILD_DIR s3://${{ secrets.BUCKET_NAME }} --delete

    - name: Invalidate CloudFront distribution
      run: |
        INVALIDATION_ID=$(aws cloudfront create-invalidation \
        --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
        --paths "${{ vars.DISTRIBUTION_INVALIDATION_PATH }}" \
        --query 'Invalidation.Id' \
        --output text)
        aws cloudfront wait invalidation-completed --distribution-id ${{ secrets.DISTRIBUTION_ID }} --id $INVALIDATION_ID
